id = "kilo"
name = "Kilo"
description = "The open source coding agent."
<<<<<<< HEAD
version = "7.2.36"
||||||| 12f7967ca4
version = "7.2.31"
=======
version = "7.3.0"
>>>>>>> yunqiqiliang/opencode-v7.3.0
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Kilo-Org/kilocode"

[agent_servers.opencode]
name = "Kilo"
icon = "./icons/opencode.svg"

[agent_servers.opencode.targets.darwin-aarch64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.36/opencode-darwin-arm64.zip"
||||||| 12f7967ca4
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-darwin-arm64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.3.0/opencode-darwin-arm64.zip"
>>>>>>> yunqiqiliang/opencode-v7.3.0
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.darwin-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.36/opencode-darwin-x64.zip"
||||||| 12f7967ca4
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-darwin-x64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.3.0/opencode-darwin-x64.zip"
>>>>>>> yunqiqiliang/opencode-v7.3.0
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.linux-aarch64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.36/opencode-linux-arm64.tar.gz"
||||||| 12f7967ca4
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-linux-arm64.tar.gz"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.3.0/opencode-linux-arm64.tar.gz"
>>>>>>> yunqiqiliang/opencode-v7.3.0
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.linux-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.36/opencode-linux-x64.tar.gz"
||||||| 12f7967ca4
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-linux-x64.tar.gz"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.3.0/opencode-linux-x64.tar.gz"
>>>>>>> yunqiqiliang/opencode-v7.3.0
cmd = "./opencode"
args = ["acp"]

[agent_servers.opencode.targets.windows-x86_64]
<<<<<<< HEAD
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.36/opencode-windows-x64.zip"
||||||| 12f7967ca4
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.2.31/opencode-windows-x64.zip"
=======
archive = "https://github.com/Kilo-Org/kilocode/releases/download/v7.3.0/opencode-windows-x64.zip"
>>>>>>> yunqiqiliang/opencode-v7.3.0
cmd = "./opencode.exe"
args = ["acp"]
